name: S4E_CDSL_Workflow

on:
  workflow_dispatch:
  push:
    branches: [ "b_github_ci" ]
  pull_request:
    branches: [ "b_github_ci" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      name: Check Modified Files   
      
    - name: Trigger Seal5 Workflow
      uses: peter-evans/repository-dispatch@v3
      with:
       token: ${{ secrets.REPO_ACCESS_TOKEN }}
       repository: ${{ 'kebi-be/seal5'}}
       event-type: s4e-cdl-event
       client-payload: '{"triggered_by": "${{ github.repository }}", "run_id": "${{ github.run_id }}"}'
    
    - name: Trigger ETISS Workflow
      uses: peter-evans/repository-dispatch@v3
      with:
        token: ${{ secrets.REPO_ACCESS_TOKEN }}
        repository: ${{ 'kebi-be/etiss' }}
        event-type: s4e-cdl-event
        client-payload: '{"triggered_by": "${{ github.repository }}", "run_id": "${{ github.run_id }}"}'
        
