name: S4E_CDSL_Workflow

on:
  workflow_dispatch:
  push:
    branches: [ "b_github_ci" ]
  pull_request:
    branches: [ "b_github_ci" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      name: Check Modified Files      
    - run: |
          ls -al
          pwd
          git fetch origin main:main
          var=$(git diff --name-only --diff-filter=d main~ main) 
          echo "List of changed files: "$var
    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: riscv-core-dsl-files
        path: /home/runner/work/riscv-coredsl-extensions/riscv-coredsl-extensions/*.core_desc      
        
    - name: Trigger Seal5 Workflow
      uses: peter-evans/repository-dispatch@v3
      with:
        token: ${{ secrets.REPO_ACCESS_TOKEN }}
        repository: ${{ 'kebi-be/seal5'}}
        event-type: s4e-cdl-event
        client-payload: '{"triggered_by": "${{ github.repository }}", "run_id": "${{ github.run_id }}"}'
    
    - name: Trigger ETISS Workflow
      uses: peter-evans/repository-dispatch@v3
      with:
        token: ${{ secrets.REPO_ACCESS_TOKEN }}
        repository: ${{ 'kebi-be/etiss_wysiwyng' }}
        event-type: s4e-cdl-event
        client-payload: '{"triggered_by": "${{ github.repository }}", "run_id": "${{ github.run_id }}"}'
        
